keys:
  - &voltex age1zwgym2vq9sldmnj60r882h9k34fw4g4x32zszg8zwkzcp2s9sv8skp8d8d
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|txt)$
    key_groups:
      - age:
        - *voltex
      
