{ config, pkgs, pkgs-unstable, agenix, ... }: 
{
    environment.systemPackages = 
    (with pkgs; [
    	git
	    fish
	    neovim
	    starship
	    fastfetch
	    alacritty
	    river
	    swww
	    eww
	    thefuck
	    wideriver
	    bemenu
	    waybar # For the actual bar, may be replaced with eww at some point
	    agenix.packages.${system}.default
	    discord
	    btop
	    cava
	    pamixer
	    pavucontrol
	    bluez
	    bluez-tools
	    blueman
	    curl
        wget
        zip
        unzip
        gnutar
        gzip
        gcc
        clang
        openssl
        zellij
        ranger
        dunst
        hyprlock
        upx
        dust
        openresty
        nginx
        distrobox
        kdePackages.krdc
        libsForQt5.krdc
        hyprshot
        wl-clipboard
        libnotify
        jq
        grim
        slurp
        brightnessctl
        playerctl
        swayidle 
        thunderbird
        weechat
        nheko
        signal-desktop
        pydf
        ungoogled-chromium
    ])
    
    ++

    (with pkgs-unstable; [
        android-studio
        watchman
        jdk
        bundix
        zlib
        zlib.dev 
        deno
	    nodejs
	    nodePackages.pnpm
        zig
        rbenv
        gnumake
        ruby.devEnv
        sqlite
        libpcap
        postgresql
        postgresql.dev
        postgresql.lib
        libxml2
        libxslt
        pkg-config 
        (python3.withPackages(python-pkgs: with python-pkgs; [
            distutils
            setuptools
            pip
        ]))
    ]);
}
