#!/usr/bin/env fish

# Keybinds
riverctl map normal Super Return spawn alacritty
riverctl map normal Super Q close
riverctl map normal Super W spawn chromium
riverctl map normal Super D spawn 'bemenu-run -i --fb "#282828" --ff "#ebdbb2" --nb "#282828" --nf "#ebdbb2" --tb "#282828" --hb "#282828" --tf "#fb4934" --hf "#fabd2f" --nf "#ebdbb2" --af "#ebdbb2" --ab "#282828" -b --hp 20 -p "Application:"'

# Auto start software
riverctl spawn 'swww-daemon --format xrgb'
riverctl spawn 'eww daemon --force-wayland'
riverctl spawn 'waybar'

# General WM rules
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super+Shift BTN_LEFT resize-view
riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen

# Wideriver rules
riverctl map normal Super plus send-layout-cmd wideriver "--ratio +0.025"
riverctl map normal Super equal send-layout-cmd wideriver "--ratio 0.50"
riverctl map normal Super minus send-layout-cmd wideriver "--ratio -0.025"
riverctl map normal Super+Alt plus send-layout-cmd wideriver "--count +1"
riverctl map normal Super+Alt equal send-layout-cmd wideriver "--count 1"
riverctl map normal Super+Alt minus send-layout-cmd wideriver "--count -1"

# Tags
for i in $(seq 1 9)
    set tags (math "2 ^ ($i - 1)")
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
end

# Rules
riverctl rule-add ssd

#XDG
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal

# Tiling
riverctl default-layout wideriver
echo "Starting wideriver"
wideriver \
	--layout left \
	--layout-alt monocle \
	--stack dwindle \
	--count-master 1 \
	--ratio-master 0.50 \
	--count-wide-left 0 \
	--ratio-wide 0.35 \
	--no-smart-gaps \
	--inner-gaps 2 \
	--outer-gaps 4 \
	--border-width 2 \
	--border-color-focused "0x282828" \
	--border-color-unfocused "0xebdbb2" \
	--log-threshold info \
	> "/tmp/wideriver.{$XDG_VTNR}.{$USER}.log" 2>&1 &
